apply plugin: 'com.android.application'

android {
    defaultConfig {
        applicationId "rkr.tinykeyboard.inputmethod"
        compileSdk 37
        minSdkVersion 15
        targetSdkVersion 37
        versionCode 13
        versionName "0.8"
    }
    signingConfigs {
        release {
            storeFile file("release.jks")
            storePassword "android"
            keyAlias "tinykeyboard"
            keyPassword "android"
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    packaging {
        resources {
            excludes += [
                'META-INF/INDEX.LIST',
                'META-INF/*.version',
                'META-INF/version-control-info.textproto'
            ]
        }
    }
    namespace 'rkr.tinykeyboard.inputmethod'
}

dependencies {
}
