apply plugin: 'com.android.application'

android {
    defaultConfig {
        applicationId "rkr.tinykeyboard.inputmethod"
        compileSdk 37
        minSdkVersion 15
        targetSdkVersion 37
        versionCode 12
        versionName "0.12"
    }
    signingConfigs {
        release {
            storeFile file("release.jks")
            storePassword "android"
            keyAlias "tinykeyboard"
            keyPassword "android"
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'rkr.tinykeyboard.inputmethod'
}

dependencies {
}
